### PR TITLE
make it a bit easier to just put the plugin in place and have it just work.

### PR DESCRIPTION
**Pull request by DaveB93**
added autoconf, and suggest
added a better default for node name

### CODE REVIEW

**Comment by DaveB93** [comment]
Oops, I just realized my 'better default for node name' might not be a good default ( i.e. I've modified my elasticsearch.yaml to have node.name: ${HOSTNAME} on all my nodes, but there's no guarantee that anyone else did that ).    I'm not sure if you'd want to take that part of the change or not

**Comment by claygregory** [comment]
Hi @DaveB93 

Sorry for my delay in replying; thanks for the PR! I agree with you on having a usable default config, but as you said, not sure `${HOSTNAME}` is all that common among users.

I'm thinking maybe using [_local](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster.html#cluster-nodes) for the default node name… thoughts?

I'll merge the rest of this PR down as soon as I'm back in front of a computer, later today or tomorrow.

**Comment by DaveB93** [comment]
yeah, _local could work and is probably more likely to work on more machines

**Comment by claygregory** [comment]
Merged in your PR and changed the default node to `_local`. Thanks again!

**Pull request merged**
